---
- name: Create simple infra
  hosts: localhost
  roles:
    - configure_dynamic_inventory
    - create_resource_group
    - create_simple_infra

- name: Run a sample command on a new vm
  hosts: azure
  tasks:
    - name: Get a hostname of the vm
      command: hostname -f
      register: vm_hostname

    - name: Print the vm hostname
      debug:
        var: vm_hostname.stdout
